# Generated by Django 5.2.3 on 2025-06-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_usermodel_date_joined_usermodel_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="is_active",
            field=models.BooleanField(verbose_name=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="is_staff",
            field=models.BooleanField(verbose_name=False),
        ),
    ]
