# Generated by Django 5.2.3 on 2025-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_usermodel_is_active_alter_usermodel_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
