# Generated by Django 5.2.3 on 2025-06-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="creator",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
